### PR TITLE
Remove JE prefixes. Update Gemfile.

### PR DESCRIPTION
**Pull request by federicocappelli-je**

### CODE REVIEW

**Comment by AlkiviadisPapadakis-je** [comment]
LGTM

**Comment by edrutter-je** [comment]
Looks like an API change, major version bump?

**Comment by AlkiviadisPapadakis-je** [comment]
There is always something to forget, isn't there. I'll sort it out.

**Comment by AlkiviadisPapadakis-je** [comment]
@edrutter-je It has already been done.

**Comment by edrutter-je** [comment]
@AlkiviadisPapadakis-je That's already been merged and tagged. So this is another major version, no?

**Comment by AlkiviadisPapadakis-je** [comment]
@edrutter-je the changes to remove the JE prefix go along the Objc inference deprecation in Xcode 9. Wouldn't hurt putting them together.

**Pull request merged**
